version: 2
jobs:
  build:
    docker: 
      - image: microsoft/dotnet:2.1-sdk
        environment:
          DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout

      - run:
          name: Build and Test
          command: |
            dotnet build -c Release src/MongoDistributedCache/MongoDistributedCache.csproj
            dotnet test "--logger:trx;LogFileName=results.xml" src/MongoDistributedCache.Tests/MongoDistributedCache.Tests.csproj
            dotnet pack -c Release --include-source --include-symbols src/MongoDistributedCache/MongoDistributedCache.csproj

      - store_test_results:
          path: src/MongoDistributedCache.Tests/TestResults

      - store_artifacts:
          path: src/MongoDistributedCache/bin/Release
          destination: artifacts

      - persist_to_workspace:
          root: src/MongoDistributedCache/bin/Release
          paths:
            - "*.nupkg"

  deployToNuget:
    docker:
      - image: microsoft/dotnet:2.1-sdk
        environment:
          DEBIAN_FRONTEND: "noninteractive"
    steps:
      - attach_workspace:
        at: artifacts

workflows:
  version: 2
  deployment-pipeline:
    jobs:
      - build
      - deployApproval:
          type: approval
          requires:
            - build
      - deployToNuget:
          requires:
            - build
            - deployApproval