version: 2
jobs:
  buildAndTest:
    docker: 
      - image: microsoft/dotnet:2.1-sdk
        environment:
          DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run:
            name: Build and Test
            command: |
              dotnet build src/MongoDistributedCache/MongoDistributedCache.csproj
              dotnet test src/MongoDistributedCache.Tests/MongoDistributedCache.Tests.csproj

  buildWithVersion:
    docker: 
      - image: microsoft/dotnet:2.1-sdk
        environment:
          DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout

      - run:
          name: Install NodeJS and npm
          command: |
            apt-get update
            curl -sL https://deb.nodesource.com/setup_10.x | bash -
            apt-get install -y nodejs

      - run:
          name: Install semantic-release and supporting packages
          command: |
            npm install --global npx
            npm install --global semantic-release
            npm install --global @semantic-release/changelog
            npm install --global @semantic-release/git
            npm install --global @semantic-release/exec

      - run:
          name: Build and Test With Version
          command: |
            semanticReleaseOutput=$(npx semantic-release --dry-run)
            echo "$semanticReleaseOutput"
            versionNumber=$(echo "$semanticReleaseOutput" | grep -oP "^.+next release version is \K(.*)$")
            dotnet build -c Release /p:Version=$versionNumber src/MongoDistributedCache/MongoDistributedCache.csproj
            dotnet test src/MongoDistributedCache.Tests/MongoDistributedCache.Tests.csproj
            dotnet pack -c Release /p:Version=$versionNumber src/MongoDistributedCache/MongoDistributedCache.csproj

      - store_artifacts:
          path: src/MongoDistributedCache/bin/Release
          destination: artifacts

      - persist_to_workspace:
          root: src/MongoDistributedCache/bin/Release
          paths:
            - "*.nupkg"

  deployToNuget:
    docker:
      - image: microsoft/dotnet:2.1-sdk
        environment:
          DEBIAN_FRONTEND: "noninteractive"
    steps:
      - attach_workspace:
          at: artifacts

      - checkout

      - run:
          name: Install NodeJS and npm
          command: |
            apt-get update
            curl -sL https://deb.nodesource.com/setup_10.x | bash -
            apt-get install -y nodejs

      - run:
          name: Install npx and semantic-release
          command: |
          npm install --global npx
          npm install --global semantic-release
          npm install --global @semantic-release/changelog
          npm install --global @semantic-release/git
          npm install --global @semantic-release/exec
          npx semantic-release

workflows:
  version: 2
  deployment-pipeline:
    jobs:
      - buildAndTest
      - buildWithVersionApproval:
          type: approval
          requires:
            - buildAndTest
      - buildWithVersion:
          requires:
            - buildWithVersionApproval
            - buildAndTest
      - deployApproval:
          type: approval
          requires:
            - buildAndTest
            - buildWithVersion
      - deployToNuget:
          requires:
            - buildAndTest
            - buildWithVersion
            - deployApproval