version: 2
jobs:
  build:
    docker: 
      - image: microsoft/dotnet:2.1-sdk
        environment:
          DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            dotnet build -c Release src/MongoDistributedCache/MongoDistributedCache.csproj
            dotnet test src/MongoDistributedCache.Tests/MongoDistributedCache.Tests.csproj
#            dotnet pack src/MongoDistributedCache/MongoDistributedCache/MongoDistributedCache.csproj
      - store_artifacts:
          path: artifacts
